import sys

filenames = ["requirements.txt", "requirements-dev.txt"]

for filename in filenames:
    with open(filename, 'r') as f:
        lines = f.readlines()

    with open(filename, 'w') as f:
        for line in lines:
            if line.startswith("# This file is autogenerated by pip-compile with Python"):
                f.write(f"# This file is autogenerated by pip-compile with Python {sys.version}\n")
            else:
                f.write(line)
